name: Expo CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Type check (TypeScript)
        run: npx tsc --noEmit

      - name: Run linter
        run: npm run lint

      # Descomenta si tienes tests configurados
      # - name: Run tests
      #   run: npm test

      # Validar configuración de Expo
      - name: Expo doctor
        run: npx expo doctor

      # Opcional: verificar que compila
      # - name: Build Expo app
      #   run: npx expo export
