name: React Native CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '23' 
        
    - name: Install dependencies
      run: npm install
      
    - name: Run tests
      run: npm test
      
  build-android:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '23'
        
    - name: Install dependencies
      run: npm install
      
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
        
    - name: Build Android
      run: |
        cd android
        ./gradlew assembleRelease
        
  build-ios:
    needs: test
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '23'
        
    - name: Install dependencies
      run: npm install
      
    - name: Install CocoaPods
      run: |
        brew install cocoapods
        cd ios && pod install && cd ..