name: React Native CI/CD

on:
  push:
    branches: [main, develop]  # Trigger en estos branches
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # Usa la versión compatible con tu proyecto

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test  # Ajusta según tu configuración de tests (jest, etc.)

  build-android:
    needs: test  # Depende del job 'test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build Android
        run: |
          cd android
          ./gradlew assembleRelease  # Build de producción
        env:
          JAVA_HOME: /usr/lib/jvm/temurin-11-jdk-amd64  # Requerido para Android

  deploy:
    needs: build-android
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Solo ejecutar en main
    steps:
      - uses: actions/checkout@v4

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: android/app/build/outputs/apk/release/app-release.apk